Traceback (most recent call last):
  File "/home/anri/Documents/anaconda3/envs/jupyterbook/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/home/anri/Documents/anaconda3/envs/jupyterbook/lib/python3.10/site-packages/nbclient/client.py", line 1314, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/anri/Documents/anaconda3/envs/jupyterbook/lib/python3.10/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
  File "/home/anri/Documents/anaconda3/envs/jupyterbook/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/anri/Documents/anaconda3/envs/jupyterbook/lib/python3.10/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "/home/anri/Documents/anaconda3/envs/jupyterbook/lib/python3.10/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/home/anri/Documents/anaconda3/envs/jupyterbook/lib/python3.10/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import pandas as pd
import matplotlib.pyplot as plt

# Load the CSV data into a DataFrame
df = pd.read_csv('wages.csv', delimiter=';')

# Extract relevant columns for plotting
# We'll use columns for jobs at or below the minimum wage
# And rows for different age categories

# Select rows for age categories and relevant columns for number of people earning minimum wage
# Assuming 'Leeftijd' is the Dutch term for 'Age'
age_categories = df[df.iloc[:, 0].str.startswith('Leeftijd')].iloc[:, [0, 1]]

# Extract the amount of people earning the minimum wage and convert to numeric
people_count = age_categories.iloc[:, 2].apply(lambda x: float(x.replace(',', '.')))

# Extract age categories
age_labels = age_categories.iloc[:, 0].str.split(': ').str[1]

# Plotting
plt.figure(figsize=(10, 8))
plt.barh(age_labels, people_count, color='skyblue')  # Adjust color as desired

plt.xlabel('Number of People Earning Minimum Wage (in thousands)')
plt.ylabel('Age Categories')
plt.title('Number of People Earning Minimum Wage by Age Category')

plt.gca().invert_yaxis()  # Invert y-axis to have the youngest at the top

plt.tight_layout()
plt.show()

------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mIndexError[0m                                Traceback (most recent call last)
Cell [0;32mIn[2], line 16[0m
[1;32m     13[0m age_categories [38;5;241m=[39m df[df[38;5;241m.[39miloc[:, [38;5;241m0[39m][38;5;241m.[39mstr[38;5;241m.[39mstartswith([38;5;124m'[39m[38;5;124mLeeftijd[39m[38;5;124m'[39m)][38;5;241m.[39miloc[:, [[38;5;241m0[39m, [38;5;241m1[39m]]
[1;32m     15[0m [38;5;66;03m# Extract the amount of people earning the minimum wage and convert to numeric[39;00m
[0;32m---> 16[0m people_count [38;5;241m=[39m [43mage_categories[49m[38;5;241;43m.[39;49m[43miloc[49m[43m[[49m[43m:[49m[43m,[49m[43m [49m[38;5;241;43m2[39;49m[43m][49m[38;5;241m.[39mapply([38;5;28;01mlambda[39;00m x: [38;5;28mfloat[39m(x[38;5;241m.[39mreplace([38;5;124m'[39m[38;5;124m,[39m[38;5;124m'[39m, [38;5;124m'[39m[38;5;124m.[39m[38;5;124m'[39m)))
[1;32m     18[0m [38;5;66;03m# Extract age categories[39;00m
[1;32m     19[0m age_labels [38;5;241m=[39m age_categories[38;5;241m.[39miloc[:, [38;5;241m0[39m][38;5;241m.[39mstr[38;5;241m.[39msplit([38;5;124m'[39m[38;5;124m: [39m[38;5;124m'[39m)[38;5;241m.[39mstr[[38;5;241m1[39m]

File [0;32m~/Documents/anaconda3/envs/jupyterbook/lib/python3.10/site-packages/pandas/core/indexing.py:1184[0m, in [0;36m_LocationIndexer.__getitem__[0;34m(self, key)[0m
[1;32m   1182[0m     [38;5;28;01mif[39;00m [38;5;28mself[39m[38;5;241m.[39m_is_scalar_access(key):
[1;32m   1183[0m         [38;5;28;01mreturn[39;00m [38;5;28mself[39m[38;5;241m.[39mobj[38;5;241m.[39m_get_value([38;5;241m*[39mkey, takeable[38;5;241m=[39m[38;5;28mself[39m[38;5;241m.[39m_takeable)
[0;32m-> 1184[0m     [38;5;28;01mreturn[39;00m [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43m_getitem_tuple[49m[43m([49m[43mkey[49m[43m)[49m
[1;32m   1185[0m [38;5;28;01melse[39;00m:
[1;32m   1186[0m     [38;5;66;03m# we by definition only have the 0th axis[39;00m
[1;32m   1187[0m     axis [38;5;241m=[39m [38;5;28mself[39m[38;5;241m.[39maxis [38;5;129;01mor[39;00m [38;5;241m0[39m

File [0;32m~/Documents/anaconda3/envs/jupyterbook/lib/python3.10/site-packages/pandas/core/indexing.py:1690[0m, in [0;36m_iLocIndexer._getitem_tuple[0;34m(self, tup)[0m
[1;32m   1689[0m [38;5;28;01mdef[39;00m [38;5;21m_getitem_tuple[39m([38;5;28mself[39m, tup: [38;5;28mtuple[39m):
[0;32m-> 1690[0m     tup [38;5;241m=[39m [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43m_validate_tuple_indexer[49m[43m([49m[43mtup[49m[43m)[49m
[1;32m   1691[0m     [38;5;28;01mwith[39;00m suppress(IndexingError):
[1;32m   1692[0m         [38;5;28;01mreturn[39;00m [38;5;28mself[39m[38;5;241m.[39m_getitem_lowerdim(tup)

File [0;32m~/Documents/anaconda3/envs/jupyterbook/lib/python3.10/site-packages/pandas/core/indexing.py:966[0m, in [0;36m_LocationIndexer._validate_tuple_indexer[0;34m(self, key)[0m
[1;32m    964[0m [38;5;28;01mfor[39;00m i, k [38;5;129;01min[39;00m [38;5;28menumerate[39m(key):
[1;32m    965[0m     [38;5;28;01mtry[39;00m:
[0;32m--> 966[0m         [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43m_validate_key[49m[43m([49m[43mk[49m[43m,[49m[43m [49m[43mi[49m[43m)[49m
[1;32m    967[0m     [38;5;28;01mexcept[39;00m [38;5;167;01mValueError[39;00m [38;5;28;01mas[39;00m err:
[1;32m    968[0m         [38;5;28;01mraise[39;00m [38;5;167;01mValueError[39;00m(
[1;32m    969[0m             [38;5;124m"[39m[38;5;124mLocation based indexing can only have [39m[38;5;124m"[39m
[1;32m    970[0m             [38;5;124mf[39m[38;5;124m"[39m[38;5;124m[[39m[38;5;132;01m{[39;00m[38;5;28mself[39m[38;5;241m.[39m_valid_types[38;5;132;01m}[39;00m[38;5;124m] types[39m[38;5;124m"[39m
[1;32m    971[0m         ) [38;5;28;01mfrom[39;00m [38;5;21;01merr[39;00m

File [0;32m~/Documents/anaconda3/envs/jupyterbook/lib/python3.10/site-packages/pandas/core/indexing.py:1592[0m, in [0;36m_iLocIndexer._validate_key[0;34m(self, key, axis)[0m
[1;32m   1590[0m     [38;5;28;01mreturn[39;00m
[1;32m   1591[0m [38;5;28;01melif[39;00m is_integer(key):
[0;32m-> 1592[0m     [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43m_validate_integer[49m[43m([49m[43mkey[49m[43m,[49m[43m [49m[43maxis[49m[43m)[49m
[1;32m   1593[0m [38;5;28;01melif[39;00m [38;5;28misinstance[39m(key, [38;5;28mtuple[39m):
[1;32m   1594[0m     [38;5;66;03m# a tuple should already have been caught by this point[39;00m
[1;32m   1595[0m     [38;5;66;03m# so don't treat a tuple as a valid indexer[39;00m
[1;32m   1596[0m     [38;5;28;01mraise[39;00m IndexingError([38;5;124m"[39m[38;5;124mToo many indexers[39m[38;5;124m"[39m)

File [0;32m~/Documents/anaconda3/envs/jupyterbook/lib/python3.10/site-packages/pandas/core/indexing.py:1685[0m, in [0;36m_iLocIndexer._validate_integer[0;34m(self, key, axis)[0m
[1;32m   1683[0m len_axis [38;5;241m=[39m [38;5;28mlen[39m([38;5;28mself[39m[38;5;241m.[39mobj[38;5;241m.[39m_get_axis(axis))
[1;32m   1684[0m [38;5;28;01mif[39;00m key [38;5;241m>[39m[38;5;241m=[39m len_axis [38;5;129;01mor[39;00m key [38;5;241m<[39m [38;5;241m-[39mlen_axis:
[0;32m-> 1685[0m     [38;5;28;01mraise[39;00m [38;5;167;01mIndexError[39;00m([38;5;124m"[39m[38;5;124msingle positional indexer is out-of-bounds[39m[38;5;124m"[39m)

[0;31mIndexError[0m: single positional indexer is out-of-bounds

